// Per-role model routing (v0.2.0): merging the plugin's own agents/*.md
// defaults with an optional global file, an optional named profile inside
// it, and an optional docs/foundry.json project override, then generating
// .claude/agents/foundry-<role>.md from the result. foundry_config_show is
// read-only; foundry_agents_sync is the only tool that writes.
//
// Template validation (templates/foundry.config.example.json and
// templates/ccr/*.json) is added alongside the templates themselves, not
// here.

import {
  finish, ok, eq, isError,
  ROOT, mkDir, plannedRepo, withServer,
  readFile, writeFile, hasFile, git, writeGlobalConfig, splitFrontmatter,
} from "./harness.mjs";

const ROLES = ["planner", "implementer", "reviewer", "summarizer"];
const AGENT_FILE = (role) => `.claude/agents/foundry-${role}.md`;

/** The plugin's own default agent file for a role: frontmatter plus body. */
const pluginAgent = (role) => splitFrontmatter(readFile(ROOT, `agents/${role}.md`));

/** A fresh directory to hold a global-config fixture, separate from any project repo. */
const cfgDir = () => mkDir("foundry-cfg-");

// ---------------------------------------------------------------- defaults, no global file

{
  const repo = plannedRepo();
  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.globalConfig, "none", "no global config file is present");
    eq(cfg.profile, null, "no profile is selected");
    eq(cfg.projectOverride, false, "the project's foundry.json carries no roles or permissionMode");
    eq(cfg.permissionMode, "acceptEdits", "the default permission mode is acceptEdits");
    eq(cfg.permissionModeSource, "default", "...with source default");
    eq(cfg.agentsGenerated.join(","), "", "nothing has been generated yet");
    eq(cfg.agentsStale.join(","), "", "nothing to be stale, either");
    for (const role of ROLES) {
      const { frontmatter: fm } = pluginAgent(role);
      eq(cfg.roles[role].model, fm.model, `${role}'s default model matches the plugin agent`);
      eq(cfg.roles[role].effort, fm.effort, `${role}'s default effort matches the plugin agent`);
      eq(cfg.roles[role].source.model, "default", `${role}'s model source is default`);
      eq(cfg.roles[role].source.effort, "default", `${role}'s effort source is default`);
      eq(cfg.roles[role].agent, `foundry-${role}`, `${role}'s reported agent name is foundry-${role}`);
    }
  });
}

// ---------------------------------------------------------------- sync writes four files

{
  const repo = plannedRepo();
  await withServer(repo, async ({ call }) => {
    const r = await call("foundry_agents_sync");
    eq(r.changed.join(","), ROLES.join(","), "sync writes all four roles the first time");
    eq(r.unchanged.join(","), "", "nothing is unchanged yet");
    eq(r.exclude, "added", "the exclude pattern is added");
    eq(r.dir, ".claude/agents", "the reported directory is relative to the project");
    eq(git(repo, ["status", "--porcelain"]), "", "the generated files are excluded, so the tree stays clean");

    const exclude = readFile(repo, ".git/info/exclude");
    ok(exclude.includes(".claude/agents/foundry-*.md"), "the pattern is present in .git/info/exclude");
    eq((exclude.match(/foundry-\*\.md/g) || []).length, 1, "the pattern appears exactly once");

    const comment = "<!-- generated by foundry_agents_sync; edit config, not this file -->\n\n";
    for (const role of ROLES) {
      ok(hasFile(repo, AGENT_FILE(role)), `${AGENT_FILE(role)} exists`);
      const text = readFile(repo, AGENT_FILE(role));
      const { frontmatter: fm, body } = splitFrontmatter(text);
      const plugin = pluginAgent(role);
      eq(fm.name, `foundry-${role}`, `${role}'s generated name`);
      eq(fm.description, plugin.frontmatter.description, `${role}'s description is copied verbatim`);
      eq(fm.model, plugin.frontmatter.model, `${role}'s model matches the plugin default`);
      eq(fm.effort, plugin.frontmatter.effort, `${role}'s effort matches the plugin default`);
      eq(fm.permissionMode, "acceptEdits", `${role}'s permissionMode defaults to acceptEdits`);
      eq((fm.skills || []).join(","), (plugin.frontmatter.skills || []).join(","), `${role}'s skills match the plugin default`);
      eq(fm.color, plugin.frontmatter.color, `${role}'s color matches the plugin default`);
      ok(body.startsWith(comment), `${role}'s body starts with the generated-by comment`);
      const expectedRest = plugin.body.replace(/^\n+/, "").replace(/\s+$/, "") + "\n";
      eq(body.slice(comment.length), expectedRest, `${role}'s body is otherwise the plugin agent's body, trimmed`);
      ok(text.endsWith("\n") && !text.endsWith("\n\n"), `${role}'s generated file ends with exactly one newline`);
    }
  });
}

// ---------------------------------------------------------------- a second sync is a no-op

{
  const repo = plannedRepo();
  await withServer(repo, async ({ call }) => {
    await call("foundry_agents_sync");
    const before = ROLES.map((role) => readFile(repo, AGENT_FILE(role)));

    const r2 = await call("foundry_agents_sync");
    eq(r2.changed.join(","), "", "nothing changes on a second, identical sync");
    eq(r2.unchanged.join(","), ROLES.join(","), "all four roles are reported unchanged");
    eq(r2.exclude, "present", "the exclude pattern is already present");

    const after = ROLES.map((role) => readFile(repo, AGENT_FILE(role)));
    eq(JSON.stringify(after), JSON.stringify(before), "file contents are byte-identical after the second sync");
    const exclude = readFile(repo, ".git/info/exclude");
    eq((exclude.match(/foundry-\*\.md/g) || []).length, 1, "the pattern still appears exactly once");
  });
}

// ---------------------------------------------------------------- foundry_next before/after sync

{
  const repo = plannedRepo();
  await withServer(repo, async ({ call }) => {
    let n = await call("foundry_next");
    eq(n.stage, "implement", "a freshly planned repo has open tasks");
    eq(n.agent, "foundry:implementer", "before sync, the plugin agent name is used");
    const modelBefore = n.model;
    ok(modelBefore, "a resolved model is reported even before sync");

    let s = await call("foundry_status");
    eq(s.agentsGenerated.join(","), "", "nothing generated yet");

    await call("foundry_agents_sync");

    n = await call("foundry_next");
    eq(n.agent, "foundry-implementer", "after sync, the generated agent name is used");
    eq(n.model, modelBefore, "the resolved model is unchanged by sync");

    s = await call("foundry_status");
    eq(s.agentsGenerated.join(","), ROLES.join(","), "status reports all four roles as generated");
  });
}

// ---------------------------------------------------------------- global file overrides

{
  const repo = plannedRepo();
  const globalPath = writeGlobalConfig(cfgDir(), {
    roles: {
      implementer: { model: "claude-sonnet-5" },
      summarizer: { effort: "low" },
    },
    permissionMode: "bypassPermissions",
  });
  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.globalConfig, globalPath, "the global config path is reported");
    eq(cfg.roles.implementer.model, "claude-sonnet-5", "the global file overrides the implementer's model");
    eq(cfg.roles.implementer.source.model, "global", "...with source global");
    eq(cfg.roles.implementer.effort, "medium", "the implementer's effort is untouched (merge is per key)");
    eq(cfg.roles.implementer.source.effort, "default", "...with source default");
    eq(cfg.roles.summarizer.effort, "low", "the global file overrides the summarizer's effort");
    eq(cfg.roles.summarizer.source.effort, "global", "...with source global");
    eq(cfg.roles.planner.source.model, "default", "the planner is untouched");
    eq(cfg.permissionMode, "bypassPermissions", "the global permissionMode wins over the acceptEdits default");
    eq(cfg.permissionModeSource, "global", "...with source global");

    await call("foundry_agents_sync");
    const impl = splitFrontmatter(readFile(repo, AGENT_FILE("implementer"))).frontmatter;
    eq(impl.model, "claude-sonnet-5", "the generated implementer file carries the global model");
    eq(impl.effort, "medium", "...and keeps the default effort");
    eq(impl.permissionMode, "bypassPermissions", "...and carries the global permissionMode");
  }, { env: { FOUNDRY_CONFIG: globalPath } });
}

// ---------------------------------------------------------------- profile selected via env

{
  const repo = plannedRepo();
  const globalPath = writeGlobalConfig(cfgDir(), {
    profiles: {
      local: {
        implementer: { model: "ollama,qwen3.6:35b-a3b" },
        reviewer: { model: "openrouter,deepseek/deepseek-v4-pro" },
      },
    },
  });
  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.profile, "local", "the env-selected profile is reported");
    eq(cfg.profileSource, "env", "...with source env");
    eq(cfg.roles.implementer.model, "ollama,qwen3.6:35b-a3b", "the profile overrides the implementer's model");
    eq(cfg.roles.implementer.effort, undefined, "effort is dropped for a non-Anthropic model");
    eq(cfg.effortDropped.implementer, "medium", "the dropped effort is reported");
    eq(cfg.roles.reviewer.model, "openrouter,deepseek/deepseek-v4-pro", "the profile overrides the reviewer's model");
    eq(cfg.roles.reviewer.effort, undefined, "effort is dropped for the reviewer too");
    eq(cfg.roles.planner.model, "fable", "the planner is untouched by the profile");
    eq(cfg.roles.planner.effort, "high", "...and keeps its effort");

    await call("foundry_agents_sync");
    const impl = splitFrontmatter(readFile(repo, AGENT_FILE("implementer"))).frontmatter;
    eq(impl.model, "ollama,qwen3.6:35b-a3b", "generated implementer file carries the profile's model");
    eq(impl.effort, undefined, "generated implementer file has no effort line");
    const rev = splitFrontmatter(readFile(repo, AGENT_FILE("reviewer"))).frontmatter;
    eq(rev.effort, undefined, "generated reviewer file has no effort line either");
    const pln = splitFrontmatter(readFile(repo, AGENT_FILE("planner"))).frontmatter;
    eq(pln.model, "fable", "generated planner file is untouched");
    eq(pln.effort, "high", "...and keeps its effort");

    const n = await call("foundry_next");
    eq(n.model, "ollama,qwen3.6:35b-a3b", "foundry_next reports the profile's implementer model");
  }, { env: { FOUNDRY_CONFIG: globalPath, FOUNDRY_PROFILE: "local" } });
}

// ---------------------------------------------------------------- profile selected via the file itself

{
  const repo = plannedRepo();
  const globalPath = writeGlobalConfig(cfgDir(), {
    profile: "local",
    profiles: {
      local: { implementer: { model: "ollama,qwen3.6:35b-a3b" } },
      cheap: { implementer: { model: "haiku", effort: "medium" } },
    },
  });
  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.profile, "local", "the file's own \"profile\" key is used when FOUNDRY_PROFILE is unset");
    eq(cfg.profileSource, "global", "...with source global");
    eq(cfg.roles.implementer.model, "ollama,qwen3.6:35b-a3b", "the file-selected profile applies");
  }, { env: { FOUNDRY_CONFIG: globalPath } });

  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.profile, "cheap", "FOUNDRY_PROFILE overrides the file's own \"profile\" key");
    eq(cfg.profileSource, "env", "...with source env");
    eq(cfg.roles.implementer.model, "haiku", "the env-selected profile applies instead");
  }, { env: { FOUNDRY_CONFIG: globalPath, FOUNDRY_PROFILE: "cheap" } });
}

// ---------------------------------------------------------------- project override

{
  const repo = plannedRepo();
  const globalPath = writeGlobalConfig(cfgDir(), {
    profiles: { local: { implementer: { model: "ollama,qwen3.6:35b-a3b" } } },
    permissionMode: "bypassPermissions",
  });
  const existing = JSON.parse(readFile(repo, "docs/foundry.json"));
  writeFile(repo, "docs/foundry.json", `${JSON.stringify({ ...existing, roles: { reviewer: { model: "haiku" } }, permissionMode: "default" }, null, 2)}\n`);
  git(repo, ["add", "-A"]);
  git(repo, ["commit", "-qm", "docs: project routing override"]);

  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.projectOverride, true, "the project override is detected");
    eq(cfg.roles.reviewer.model, "haiku", "the project overrides the reviewer's model");
    eq(cfg.roles.reviewer.source.model, "project", "...with source project");
    eq(cfg.roles.reviewer.effort, "high", "haiku is an Anthropic alias, so effort is emitted again");
    eq(cfg.roles.implementer.model, "ollama,qwen3.6:35b-a3b", "the implementer still comes from the profile, untouched by the project");
    eq(cfg.roles.planner.source.model, "default", "the planner is untouched by either layer");
    eq(cfg.permissionMode, "default", "the project's permissionMode overrides the global one");
    eq(cfg.permissionModeSource, "project", "...with source project");

    const v = await call("foundry_verify", { files: ["hello.txt"] });
    ok(v.results.length >= 1, "foundry_verify still works; the routing keys leave the rest of foundry.json alone");
  }, { env: { FOUNDRY_CONFIG: globalPath, FOUNDRY_PROFILE: "local" } });
}

// ---------------------------------------------------------------- effort survives for claude-* ids

{
  const repo = plannedRepo();
  const globalPath = writeGlobalConfig(cfgDir(), { roles: { planner: { model: "claude-fable-5-1" } } });
  await withServer(repo, async ({ call }) => {
    const cfg = await call("foundry_config_show");
    eq(cfg.roles.planner.model, "claude-fable-5-1", "the planner's model is overridden to a full claude-* id");
    eq(cfg.roles.planner.effort, "high", "effort survives because claude-* counts as an Anthropic model");
    eq(cfg.effortDropped.planner, undefined, "nothing was dropped for the planner");
  }, { env: { FOUNDRY_CONFIG: globalPath } });
}

// ---------------------------------------------------------------- stale detection

{
  const repo = plannedRepo();
  const dir = cfgDir();

  await withServer(repo, async ({ call }) => {
    await call("foundry_agents_sync");
    const cfg = await call("foundry_config_show");
    eq(cfg.agentsStale.join(","), "", "freshly synced agents are not stale");
  }, { env: { FOUNDRY_CONFIG: writeGlobalConfig(dir, { roles: { implementer: { model: "sonnet" } } }) } });

  // Change the global file without re-syncing.
  const changedPath = writeGlobalConfig(dir, { roles: { implementer: { model: "haiku" } } });
  await withServer(repo, async ({ call }) => {
    let cfg = await call("foundry_config_show");
    eq(cfg.agentsStale.join(","), "implementer", "config_show notices the implementer's generated file is now stale");
    ok(readFile(repo, AGENT_FILE("implementer")).includes("model: sonnet"), "config_show never rewrites the file itself");

    const r = await call("foundry_agents_sync");
    eq(r.changed.join(","), "implementer", "sync catches the stale file up to the new config");

    cfg = await call("foundry_config_show");
    eq(cfg.agentsStale.join(","), "", "nothing is stale after a fresh sync");
  }, { env: { FOUNDRY_CONFIG: changedPath } });
}

// ---------------------------------------------------------------- refusals

{
  const repo = plannedRepo();

  const cases = [
    [{ roles: { tester: { model: "x" } } }, /unknown role 'tester'/, "unknown role name"],
    [{ roles: { planner: { temperature: 1 } } }, /unknown key 'temperature'/, "unknown key in a role"],
    [{ roles: { planner: { effort: "ultra" } } }, /effort/, "bad effort value"],
    [{ permissionMode: "yolo" }, /permissionMode/, "bad permissionMode value"],
    [{ router: "x" }, /unknown key 'router'/, "unknown top-level key"],
  ];
  for (const [obj, re, label] of cases) {
    const globalPath = writeGlobalConfig(cfgDir(), obj);
    await withServer(repo, async ({ call }) => {
      isError(await call("foundry_config_show"), re, `config_show refuses: ${label}`);
      isError(await call("foundry_next"), re, `next refuses with the same kind of error: ${label}`);
      isError(await call("foundry_status"), re, `status refuses with the same kind of error: ${label}`);
      isError(await call("foundry_agents_sync"), re, `agents_sync refuses: ${label}`);
      ok(!hasFile(repo, ".claude/agents"), `.claude/agents is never created on a refused sync (${label})`);
    }, { env: { FOUNDRY_CONFIG: globalPath } });
  }

  {
    const p = writeFile(cfgDir(), "foundry-global.json", "{not json");
    await withServer(repo, async ({ call }) => {
      isError(await call("foundry_config_show"), /not valid JSON/, "invalid JSON in the global config");
    }, { env: { FOUNDRY_CONFIG: p } });
  }

  {
    const globalPath = writeGlobalConfig(cfgDir(), { profiles: { cheap: {} } });
    await withServer(repo, async ({ call }) => {
      isError(await call("foundry_config_show"), /profiles\.nope/, "FOUNDRY_PROFILE names a profile that does not exist");
    }, { env: { FOUNDRY_CONFIG: globalPath, FOUNDRY_PROFILE: "nope" } });
  }

  {
    const globalPath = writeGlobalConfig(cfgDir(), { profile: "nope" });
    await withServer(repo, async ({ call }) => {
      isError(await call("foundry_config_show"), /profiles\.nope/, "the global file's own \"profile\" key names a profile that does not exist");
    }, { env: { FOUNDRY_CONFIG: globalPath } });
  }

  {
    // An unselected profile is still validated, not only the one FOUNDRY_PROFILE picks.
    const globalPath = writeGlobalConfig(cfgDir(), {
      profiles: {
        local: { implementer: { model: "sonnet" } },
        broken: { implementer: { temperature: 1 } },
      },
    });
    await withServer(repo, async ({ call }) => {
      isError(await call("foundry_config_show"), /unknown key 'temperature'/, "an unselected profile is validated too");
    }, { env: { FOUNDRY_CONFIG: globalPath, FOUNDRY_PROFILE: "local" } });
  }
}

// ---------------------------------------------------------------- not a git repository

{
  const dir = mkDir("foundry-plain-routing-");
  await withServer(dir, async ({ call }) => {
    const r = await call("foundry_agents_sync");
    eq(r.changed.join(","), ROLES.join(","), "sync still writes the four files outside a git repository");
    eq(r.exclude, "skipped: not a git repository", "the exclude step is skipped, not an error");
    for (const role of ROLES) ok(hasFile(dir, AGENT_FILE(role)), `${role}'s file is written anyway`);
  });
}

// ---------------------------------------------------------------- description round-trips

{
  const repo = plannedRepo();
  await withServer(repo, async ({ call }) => {
    await call("foundry_agents_sync");
    for (const role of ROLES) {
      const { frontmatter: fm } = splitFrontmatter(readFile(repo, AGENT_FILE(role)));
      eq(fm.description, pluginAgent(role).frontmatter.description, `${role}'s description round-trips through the generated file exactly`);
    }
  });
}

finish();
